language: node_js
node_js:
  - "8"

services:
  - redis-server
  - mongodb

env:
 - NODE_ENV=ci
 - PORT=3000

install:
  - npm install
  - npm run build

script:
  - nohub npm run start &
  - sleep 3
  - npm run test
